
name: daily-report

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: py-actions/py-dependency-install@v3
        with:
          python-version: 3.10.5
          path: "requirements.txt"
      - name: Run email code
        run: python main.py
